spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 500MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      #???????
      column-underline: true
      #??????
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: clickhouse
    refresh: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  mapper-locations: classpath:/mapper/**/*.xml,classpath*:/cn/piesat/clickhouse/mapper/xml/*.xml
server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/javascript,application/octet-stream, application/json,application/xml,text/html,text/xml,text/plain,text/javascript

